version: 7.7.0-{build}

clone_depth: 50

build_script:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git
  - cmake -Denable_gcj_support=ON
  - cmake --build .

test_script:
  - ctest --build-config Debug -V

artifacts:
  - path: '*.dir'
    name: libgc-win32-x86_64
    type: zip
